import '../models/protocol_category.dart';
import '../models/protocol_preset.dart';
import '../models/protocol_type.dart';

class ProtocolPresetService {
  static const List<ProtocolPreset> _presets = [
    // -----------------------------------------------------------------
    // Peptides & Research
    // -----------------------------------------------------------------
    ProtocolPreset(
      name: 'Retatrutide',
      category: ProtocolCategory.peptide,
      aliases: ['Reta'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Tirzepatide',
      category: ProtocolCategory.peptide,
      aliases: ['Tirz', 'Mounjaro', 'Zepbound'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Semaglutide',
      category: ProtocolCategory.peptide,
      aliases: ['Sema', 'Ozempic', 'Wegovy'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Cagrilintide',
      category: ProtocolCategory.peptide,
      aliases: ['Cagri'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Survodutide',
      category: ProtocolCategory.peptide,
      aliases: ['Survo'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Eloralintide',
      category: ProtocolCategory.peptide,
      aliases: ['Elora'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'GHK-Cu',
      category: ProtocolCategory.peptide,
      aliases: ['GHKCu', 'Copper Peptide'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'AHK-Cu',
      category: ProtocolCategory.peptide,
      aliases: ['AHKCu'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.topical,
      defaultContainerType: 'Bottle',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'BPC-157',
      category: ProtocolCategory.peptide,
      aliases: ['BPC157', 'BPC'],
      defaultUnit: 'mcg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'TB-500',
      category: ProtocolCategory.peptide,
      aliases: ['TB500', 'TB4'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'BPC-157 + TB-500',
      category: ProtocolCategory.peptide,
      aliases: ['BPC TB', 'BPC/TB', 'BPC157 TB500'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Wolverine (Blend)',
      category: ProtocolCategory.peptide,
      aliases: ['Wolverine'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'GLOW (Blend)',
      category: ProtocolCategory.peptide,
      aliases: ['GLOW'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'KLOW (Blend)',
      category: ProtocolCategory.peptide,
      aliases: ['KLOW'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Tesamorelin',
      category: ProtocolCategory.peptide,
      aliases: ['Tesa'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'CJC-1295 (No DAC)',
      category: ProtocolCategory.peptide,
      aliases: ['CJC No DAC', 'CJC1295 No DAC', 'Mod GRF 1-29'],
      defaultUnit: 'mcg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'CJC-1295 (DAC)',
      category: ProtocolCategory.peptide,
      aliases: ['CJC DAC', 'CJC1295 DAC'],
      defaultUnit: 'mcg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Ipamorelin',
      category: ProtocolCategory.peptide,
      aliases: ['Ipa'],
      defaultUnit: 'mcg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'CJC-1295 (No DAC) + Ipamorelin',
      category: ProtocolCategory.peptide,
      aliases: ['CJC Ipa', 'CJC + Ipa'],
      defaultUnit: 'mcg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Sermorelin',
      category: ProtocolCategory.peptide,
      aliases: ['Sermo'],
      defaultUnit: 'mcg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'GHRP-2',
      category: ProtocolCategory.peptide,
      aliases: ['GHRP2'],
      defaultUnit: 'mcg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'GHRP-6',
      category: ProtocolCategory.peptide,
      aliases: ['GHRP6'],
      defaultUnit: 'mcg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Hexarelin',
      category: ProtocolCategory.peptide,
      aliases: ['Hex'],
      defaultUnit: 'mcg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'KPV',
      category: ProtocolCategory.peptide,
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'MOTS-C',
      category: ProtocolCategory.peptide,
      aliases: ['MOTSc', 'MOTS C'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'SS-31',
      category: ProtocolCategory.peptide,
      aliases: ['SS31', 'Elamipretide'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Epithalon',
      category: ProtocolCategory.peptide,
      aliases: ['Epitalon'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Thymosin Alpha-1',
      category: ProtocolCategory.peptide,
      aliases: ['TA1', 'Thymosin Alpha 1'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Thymalin',
      category: ProtocolCategory.peptide,
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Vesugen',
      category: ProtocolCategory.peptide,
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Pinealon',
      category: ProtocolCategory.peptide,
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'DSIP',
      category: ProtocolCategory.peptide,
      defaultUnit: 'mcg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Selank',
      category: ProtocolCategory.peptide,
      defaultUnit: 'mcg',
      defaultProtocolType: ProtocolType.nasal,
      defaultContainerType: 'Bottle',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Semax',
      category: ProtocolCategory.peptide,
      defaultUnit: 'mcg',
      defaultProtocolType: ProtocolType.nasal,
      defaultContainerType: 'Bottle',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Adamax 984',
      category: ProtocolCategory.peptide,
      aliases: ['Adamax984'],
      defaultUnit: 'mcg',
      defaultProtocolType: ProtocolType.nasal,
      defaultContainerType: 'Bottle',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Adamax 1032',
      category: ProtocolCategory.peptide,
      aliases: ['Adamax1032'],
      defaultUnit: 'mcg',
      defaultProtocolType: ProtocolType.nasal,
      defaultContainerType: 'Bottle',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'ARA-290',
      category: ProtocolCategory.peptide,
      aliases: ['ARA290', 'Cibinetide'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'PE-22-28',
      category: ProtocolCategory.peptide,
      aliases: ['PE2228'],
      defaultUnit: 'mcg',
      defaultProtocolType: ProtocolType.nasal,
      defaultContainerType: 'Bottle',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'LL-37',
      category: ProtocolCategory.peptide,
      aliases: ['LL37'],
      defaultUnit: 'mcg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'VIP',
      category: ProtocolCategory.peptide,
      aliases: ['Vasoactive Intestinal Peptide'],
      defaultUnit: 'mcg',
      defaultProtocolType: ProtocolType.nasal,
      defaultContainerType: 'Bottle',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'PT-141',
      category: ProtocolCategory.peptide,
      aliases: ['PT141', 'Bremelanotide'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Kisspeptin',
      category: ProtocolCategory.peptide,
      defaultUnit: 'mcg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Oxytocin',
      category: ProtocolCategory.peptide,
      defaultUnit: 'IU',
      defaultProtocolType: ProtocolType.nasal,
      defaultContainerType: 'Bottle',
      defaultInventoryUnit: 'IU',
    ),
    ProtocolPreset(
      name: 'IGF-1 LR3',
      category: ProtocolCategory.peptide,
      aliases: ['IGF1 LR3', 'IGF LR3'],
      defaultUnit: 'mcg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'MGF',
      category: ProtocolCategory.peptide,
      aliases: ['Mechano Growth Factor'],
      defaultUnit: 'mcg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'PEG-MGF',
      category: ProtocolCategory.peptide,
      aliases: ['PEG MGF'],
      defaultUnit: 'mcg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'AOD-9604',
      category: ProtocolCategory.peptide,
      aliases: ['AOD9604'],
      defaultUnit: 'mcg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'HGH Fragment 176-191',
      category: ProtocolCategory.peptide,
      aliases: ['HGH Frag', 'Frag 176-191', 'Frag176191'],
      defaultUnit: 'mcg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'NAD+',
      category: ProtocolCategory.peptide,
      aliases: ['NAD', 'Nicotinamide Adenine Dinucleotide'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Glutathione',
      category: ProtocolCategory.peptide,
      aliases: ['GSH'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: '5-Amino-1MQ',
      category: ProtocolCategory.peptide,
      aliases: ['5AM', '5 Amino 1MQ', '5A1MQ'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'SLU-PP-332',
      category: ProtocolCategory.peptide,
      aliases: ['SLU', 'SLUPP332'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.oral,
      defaultContainerType: 'Bottle',
      defaultInventoryUnit: 'capsules',
    ),
    ProtocolPreset(
      name: 'MK-677',
      category: ProtocolCategory.peptide,
      aliases: ['MK677', 'Ibutamoren'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.oral,
      defaultContainerType: 'Bottle',
      defaultInventoryUnit: 'capsules',
    ),
    ProtocolPreset(
      name: 'L-Carnitine',
      category: ProtocolCategory.peptide,
      aliases: ['Carnitine'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Lipo-C + B12',
      category: ProtocolCategory.peptide,
      aliases: ['Lipo C B12', 'Lipotropic B12'],
      defaultUnit: 'mL',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mL',
    ),
    ProtocolPreset(
      name: 'Lipo-C',
      category: ProtocolCategory.peptide,
      aliases: ['Lipo C', 'Lipotropic'],
      defaultUnit: 'mL',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mL',
    ),
    ProtocolPreset(
      name: 'Snap-8',
      category: ProtocolCategory.peptide,
      aliases: ['Snap8', 'Acetyl Octapeptide-3'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.topical,
      defaultContainerType: 'Bottle',
      defaultInventoryUnit: 'mg',
    ),

    // -----------------------------------------------------------------
    // Hormones & TRT
    // -----------------------------------------------------------------
    ProtocolPreset(
      name: 'Testosterone Cypionate',
      category: ProtocolCategory.hormonesAndTrt,
      aliases: ['Test C', 'Test Cyp', 'Cypionate'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Testosterone Enanthate',
      category: ProtocolCategory.hormonesAndTrt,
      aliases: ['Test E', 'Test Enanthate'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Testosterone Propionate',
      category: ProtocolCategory.hormonesAndTrt,
      aliases: ['Test P', 'Test Prop'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Testosterone Undecanoate',
      category: ProtocolCategory.hormonesAndTrt,
      aliases: ['Test U', 'Aveed', 'Nebido'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Sustanon 250',
      category: ProtocolCategory.hormonesAndTrt,
      aliases: ['Sustanon'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Testosterone Gel',
      category: ProtocolCategory.hormonesAndTrt,
      aliases: ['AndroGel', 'Test Gel'],
      defaultUnit: 'pump',
      defaultProtocolType: ProtocolType.topical,
      defaultContainerType: 'Bottle',
      defaultInventoryUnit: 'pumps',
    ),
    ProtocolPreset(
      name: 'HCG',
      category: ProtocolCategory.hormonesAndTrt,
      aliases: ['Human Chorionic Gonadotropin'],
      defaultUnit: 'IU',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'IU',
    ),
    ProtocolPreset(
      name: 'HMG',
      category: ProtocolCategory.hormonesAndTrt,
      aliases: ['Menotropins'],
      defaultUnit: 'IU',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'IU',
    ),
    ProtocolPreset(
      name: 'HGH / Somatropin',
      category: ProtocolCategory.hormonesAndTrt,
      aliases: ['HGH', 'Somatropin', 'Growth Hormone'],
      defaultUnit: 'IU',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'IU',
    ),
    ProtocolPreset(
      name: 'Estradiol',
      category: ProtocolCategory.hormonesAndTrt,
      aliases: ['E2'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.oral,
      defaultContainerType: 'Bottle',
      defaultInventoryUnit: 'tablets',
    ),
    ProtocolPreset(
      name: 'Estradiol Patch',
      category: ProtocolCategory.hormonesAndTrt,
      aliases: ['E2 Patch'],
      defaultUnit: 'patch',
      defaultProtocolType: ProtocolType.topical,
      defaultContainerType: 'Box',
      defaultInventoryUnit: 'patches',
    ),
    ProtocolPreset(
      name: 'Estradiol Valerate',
      category: ProtocolCategory.hormonesAndTrt,
      aliases: ['EV'],
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mg',
    ),
    ProtocolPreset(
      name: 'Progesterone',
      category: ProtocolCategory.hormonesAndTrt,
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.oral,
      defaultContainerType: 'Bottle',
      defaultInventoryUnit: 'capsules',
    ),
    ProtocolPreset(
      name: 'DHEA',
      category: ProtocolCategory.hormonesAndTrt,
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.oral,
      defaultContainerType: 'Bottle',
      defaultInventoryUnit: 'capsules',
    ),
    ProtocolPreset(
      name: 'Pregnenolone',
      category: ProtocolCategory.hormonesAndTrt,
      defaultUnit: 'mg',
      defaultProtocolType: ProtocolType.oral,
      defaultContainerType: 'Bottle',
      defaultInventoryUnit: 'capsules',
    ),

    // -----------------------------------------------------------------
    // Medications
    // -----------------------------------------------------------------
    ProtocolPreset(name: 'Metformin', category: ProtocolCategory.medication, defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Lisinopril', category: ProtocolCategory.medication, defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Losartan', category: ProtocolCategory.medication, defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Amlodipine', category: ProtocolCategory.medication, defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Valsartan', category: ProtocolCategory.medication, defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Hydrochlorothiazide', category: ProtocolCategory.medication, aliases: ['HCTZ'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Metoprolol', category: ProtocolCategory.medication, defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Propranolol', category: ProtocolCategory.medication, defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Spironolactone', category: ProtocolCategory.medication, defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Atorvastatin', category: ProtocolCategory.medication, aliases: ['Lipitor'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Rosuvastatin', category: ProtocolCategory.medication, aliases: ['Crestor'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Simvastatin', category: ProtocolCategory.medication, defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Ezetimibe', category: ProtocolCategory.medication, aliases: ['Zetia'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Levothyroxine', category: ProtocolCategory.medication, aliases: ['Synthroid'], defaultUnit: 'mcg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Liothyronine', category: ProtocolCategory.medication, aliases: ['Cytomel', 'T3'], defaultUnit: 'mcg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Omeprazole', category: ProtocolCategory.medication, aliases: ['Prilosec'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Pantoprazole', category: ProtocolCategory.medication, aliases: ['Protonix'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Famotidine', category: ProtocolCategory.medication, aliases: ['Pepcid'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Cetirizine', category: ProtocolCategory.medication, aliases: ['Zyrtec'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Loratadine', category: ProtocolCategory.medication, aliases: ['Claritin'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Fexofenadine', category: ProtocolCategory.medication, aliases: ['Allegra'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Diphenhydramine', category: ProtocolCategory.medication, aliases: ['Benadryl'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Acetaminophen', category: ProtocolCategory.medication, aliases: ['Tylenol', 'Paracetamol'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Ibuprofen', category: ProtocolCategory.medication, aliases: ['Advil', 'Motrin'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Naproxen', category: ProtocolCategory.medication, aliases: ['Aleve'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Aspirin', category: ProtocolCategory.medication, aliases: ['ASA'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Meloxicam', category: ProtocolCategory.medication, aliases: ['Mobic'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Celecoxib', category: ProtocolCategory.medication, aliases: ['Celebrex'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Amoxicillin', category: ProtocolCategory.medication, defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Azithromycin', category: ProtocolCategory.medication, aliases: ['Z-Pak', 'Zithromax'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Doxycycline', category: ProtocolCategory.medication, defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Cephalexin', category: ProtocolCategory.medication, aliases: ['Keflex'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Ciprofloxacin', category: ProtocolCategory.medication, aliases: ['Cipro'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Sertraline', category: ProtocolCategory.medication, aliases: ['Zoloft'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Fluoxetine', category: ProtocolCategory.medication, aliases: ['Prozac'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Escitalopram', category: ProtocolCategory.medication, aliases: ['Lexapro'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Bupropion', category: ProtocolCategory.medication, aliases: ['Wellbutrin'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Venlafaxine', category: ProtocolCategory.medication, aliases: ['Effexor'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Duloxetine', category: ProtocolCategory.medication, aliases: ['Cymbalta'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Buspirone', category: ProtocolCategory.medication, aliases: ['Buspar'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Hydroxyzine', category: ProtocolCategory.medication, aliases: ['Vistaril', 'Atarax'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Trazodone', category: ProtocolCategory.medication, defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Mirtazapine', category: ProtocolCategory.medication, aliases: ['Remeron'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Mixed Amphetamine Salts', category: ProtocolCategory.medication, aliases: ['Adderall'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Lisdexamfetamine', category: ProtocolCategory.medication, aliases: ['Vyvanse'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Methylphenidate', category: ProtocolCategory.medication, aliases: ['Ritalin', 'Concerta'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Atomoxetine', category: ProtocolCategory.medication, aliases: ['Strattera'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Zolpidem', category: ProtocolCategory.medication, aliases: ['Ambien'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Eszopiclone', category: ProtocolCategory.medication, aliases: ['Lunesta'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Sumatriptan', category: ProtocolCategory.medication, aliases: ['Imitrex'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Rizatriptan', category: ProtocolCategory.medication, aliases: ['Maxalt'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Topiramate', category: ProtocolCategory.medication, aliases: ['Topamax'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Albuterol', category: ProtocolCategory.medication, aliases: ['Ventolin', 'ProAir'], defaultUnit: 'puff', defaultProtocolType: ProtocolType.other, defaultContainerType: 'Container', defaultInventoryUnit: 'puffs'),
    ProtocolPreset(name: 'Montelukast', category: ProtocolCategory.medication, aliases: ['Singulair'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Fluticasone Nasal Spray', category: ProtocolCategory.medication, aliases: ['Flonase'], defaultUnit: 'spray', defaultProtocolType: ProtocolType.nasal, defaultContainerType: 'Bottle', defaultInventoryUnit: 'sprays'),
    ProtocolPreset(name: 'Insulin Glargine', category: ProtocolCategory.medication, aliases: ['Lantus', 'Basaglar'], defaultUnit: 'units', defaultProtocolType: ProtocolType.injection, defaultContainerType: 'Pen', defaultInventoryUnit: 'units'),
    ProtocolPreset(name: 'Insulin Lispro', category: ProtocolCategory.medication, aliases: ['Humalog'], defaultUnit: 'units', defaultProtocolType: ProtocolType.injection, defaultContainerType: 'Pen', defaultInventoryUnit: 'units'),
    ProtocolPreset(name: 'Empagliflozin', category: ProtocolCategory.medication, aliases: ['Jardiance'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Dapagliflozin', category: ProtocolCategory.medication, aliases: ['Farxiga'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Glipizide', category: ProtocolCategory.medication, defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Tamsulosin', category: ProtocolCategory.medication, aliases: ['Flomax'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Finasteride', category: ProtocolCategory.medication, aliases: ['Propecia', 'Proscar'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Dutasteride', category: ProtocolCategory.medication, aliases: ['Avodart'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Sildenafil', category: ProtocolCategory.medication, aliases: ['Viagra'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Tadalafil', category: ProtocolCategory.medication, aliases: ['Cialis'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Anastrozole', category: ProtocolCategory.medication, aliases: ['Arimidex'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Exemestane', category: ProtocolCategory.medication, aliases: ['Aromasin'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Enclomiphene', category: ProtocolCategory.medication, aliases: ['Enclo'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Clomiphene', category: ProtocolCategory.medication, aliases: ['Clomid'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Tamoxifen', category: ProtocolCategory.medication, aliases: ['Nolvadex'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Apixaban', category: ProtocolCategory.medication, aliases: ['Eliquis'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Rivaroxaban', category: ProtocolCategory.medication, aliases: ['Xarelto'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Isotretinoin', category: ProtocolCategory.medication, aliases: ['Accutane'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Tretinoin', category: ProtocolCategory.medication, aliases: ['Retin-A'], defaultUnit: 'application', defaultProtocolType: ProtocolType.topical, defaultContainerType: 'Tube', defaultInventoryUnit: 'g'),
    ProtocolPreset(name: 'Minoxidil', category: ProtocolCategory.medication, aliases: ['Rogaine'], defaultUnit: 'mL', defaultProtocolType: ProtocolType.topical, defaultContainerType: 'Bottle', defaultInventoryUnit: 'mL'),

    // -----------------------------------------------------------------
    // Supplements & Vitamins
    // -----------------------------------------------------------------
    ProtocolPreset(name: 'Fish Oil', category: ProtocolCategory.supplementsAndVitamins, aliases: ['Omega-3', 'Omega 3'], defaultUnit: 'capsule', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Creatine', category: ProtocolCategory.supplementsAndVitamins, aliases: ['Creatine Monohydrate'], defaultUnit: 'g', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Container', defaultInventoryUnit: 'g'),
    ProtocolPreset(name: 'Magnesium Glycinate', category: ProtocolCategory.supplementsAndVitamins, defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Magnesium Citrate', category: ProtocolCategory.supplementsAndVitamins, defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Berberine', category: ProtocolCategory.supplementsAndVitamins, defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'NAC', category: ProtocolCategory.supplementsAndVitamins, aliases: ['N-Acetyl Cysteine'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'CoQ10', category: ProtocolCategory.supplementsAndVitamins, aliases: ['Coenzyme Q10'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'softgels'),
    ProtocolPreset(name: 'Ashwagandha', category: ProtocolCategory.supplementsAndVitamins, defaultUnit: 'capsule', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Electrolytes', category: ProtocolCategory.supplementsAndVitamins, defaultUnit: 'serving', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Container', defaultInventoryUnit: 'servings'),
    ProtocolPreset(name: 'Vitamin D3', category: ProtocolCategory.supplementsAndVitamins, aliases: ['Vitamin D'], defaultUnit: 'IU', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'softgels'),
    ProtocolPreset(name: 'Vitamin K2', category: ProtocolCategory.supplementsAndVitamins, defaultUnit: 'mcg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Vitamin B12', category: ProtocolCategory.supplementsAndVitamins, aliases: ['B12'], defaultUnit: 'mcg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Vitamin C', category: ProtocolCategory.supplementsAndVitamins, defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Vitamin B Complex', category: ProtocolCategory.supplementsAndVitamins, aliases: ['B Complex'], defaultUnit: 'capsule', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Zinc', category: ProtocolCategory.supplementsAndVitamins, defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Iron', category: ProtocolCategory.supplementsAndVitamins, defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Multivitamin', category: ProtocolCategory.supplementsAndVitamins, aliases: ['Multi'], defaultUnit: 'tablet', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Melatonin', category: ProtocolCategory.supplementsAndVitamins, defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Probiotic', category: ProtocolCategory.supplementsAndVitamins, defaultUnit: 'capsule', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Collagen', category: ProtocolCategory.supplementsAndVitamins, aliases: ['Collagen Peptides'], defaultUnit: 'g', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Container', defaultInventoryUnit: 'g'),
    ProtocolPreset(name: 'Glycine', category: ProtocolCategory.supplementsAndVitamins, defaultUnit: 'g', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Container', defaultInventoryUnit: 'g'),
    ProtocolPreset(name: 'Taurine', category: ProtocolCategory.supplementsAndVitamins, defaultUnit: 'g', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Container', defaultInventoryUnit: 'g'),
    ProtocolPreset(name: 'L-Theanine', category: ProtocolCategory.supplementsAndVitamins, aliases: ['Theanine'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Alpha Lipoic Acid', category: ProtocolCategory.supplementsAndVitamins, aliases: ['ALA'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Curcumin', category: ProtocolCategory.supplementsAndVitamins, defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Turmeric', category: ProtocolCategory.supplementsAndVitamins, defaultUnit: 'capsule', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Calcium', category: ProtocolCategory.supplementsAndVitamins, defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Potassium', category: ProtocolCategory.supplementsAndVitamins, defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Selenium', category: ProtocolCategory.supplementsAndVitamins, defaultUnit: 'mcg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Biotin', category: ProtocolCategory.supplementsAndVitamins, defaultUnit: 'mcg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Folate', category: ProtocolCategory.supplementsAndVitamins, aliases: ['Folic Acid', 'Methylfolate'], defaultUnit: 'mcg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Niacin', category: ProtocolCategory.supplementsAndVitamins, aliases: ['Vitamin B3'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Riboflavin', category: ProtocolCategory.supplementsAndVitamins, aliases: ['Vitamin B2'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Thiamine', category: ProtocolCategory.supplementsAndVitamins, aliases: ['Vitamin B1'], defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'tablets'),
    ProtocolPreset(name: 'Vitamin A', category: ProtocolCategory.supplementsAndVitamins, defaultUnit: 'IU', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'softgels'),
    ProtocolPreset(name: 'Vitamin E', category: ProtocolCategory.supplementsAndVitamins, defaultUnit: 'IU', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'softgels'),
    ProtocolPreset(name: 'Psyllium Fiber', category: ProtocolCategory.supplementsAndVitamins, aliases: ['Psyllium Husk'], defaultUnit: 'g', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Container', defaultInventoryUnit: 'g'),
    ProtocolPreset(name: 'Inositol', category: ProtocolCategory.supplementsAndVitamins, defaultUnit: 'g', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Container', defaultInventoryUnit: 'g'),
    ProtocolPreset(name: 'Choline', category: ProtocolCategory.supplementsAndVitamins, defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'MSM', category: ProtocolCategory.supplementsAndVitamins, defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Glucosamine', category: ProtocolCategory.supplementsAndVitamins, defaultUnit: 'mg', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Bottle', defaultInventoryUnit: 'capsules'),
    ProtocolPreset(name: 'Beta-Alanine', category: ProtocolCategory.supplementsAndVitamins, aliases: ['Beta Alanine'], defaultUnit: 'g', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Container', defaultInventoryUnit: 'g'),
    ProtocolPreset(name: 'Citrulline Malate', category: ProtocolCategory.supplementsAndVitamins, defaultUnit: 'g', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Container', defaultInventoryUnit: 'g'),
    ProtocolPreset(name: 'Protein Powder', category: ProtocolCategory.supplementsAndVitamins, aliases: ['Whey', 'Protein'], defaultUnit: 'serving', defaultProtocolType: ProtocolType.oral, defaultContainerType: 'Container', defaultInventoryUnit: 'servings'),

    // -----------------------------------------------------------------
    // Other & Wellness
    // -----------------------------------------------------------------
    ProtocolPreset(
      name: 'Lemon Bottle',
      category: ProtocolCategory.otherWellness,
      aliases: ['LemonBottle'],
      defaultUnit: 'mL',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mL',
    ),
    ProtocolPreset(
      name: 'Kabelline',
      category: ProtocolCategory.otherWellness,
      defaultUnit: 'mL',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mL',
    ),
    ProtocolPreset(
      name: 'Dr. Lipo+',
      category: ProtocolCategory.otherWellness,
      aliases: ['Dr Lipo', 'Dr Lipo+'],
      defaultUnit: 'mL',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mL',
    ),
    ProtocolPreset(
      name: 'Lipo Lab PPC',
      category: ProtocolCategory.otherWellness,
      aliases: ['Lipo Lab'],
      defaultUnit: 'mL',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mL',
    ),
    ProtocolPreset(
      name: 'Mesotherapy Blend',
      category: ProtocolCategory.otherWellness,
      aliases: ['Meso Blend', 'Mesotherapy'],
      defaultUnit: 'mL',
      defaultProtocolType: ProtocolType.injection,
      defaultContainerType: 'Vial',
      defaultInventoryUnit: 'mL',
    ),
  ];

  List<ProtocolPreset> getByCategory(ProtocolCategory category) {
    final presets = _presets
        .where((preset) => preset.category == category)
        .toList();

    presets.sort(
      (first, second) =>
          first.name.toLowerCase().compareTo(second.name.toLowerCase()),
    );

    return presets;
  }

  List<ProtocolPreset> search({
    required ProtocolCategory category,
    required String query,
  }) {
    final categoryPresets = getByCategory(category);

    if (query.trim().isEmpty) {
      return categoryPresets;
    }

    return categoryPresets
        .where((preset) => preset.matchesQuery(query))
        .toList();
  }

  ProtocolPreset? findByName({
    required ProtocolCategory category,
    required String name,
  }) {
    for (final preset in getByCategory(category)) {
      if (preset.matchesExactNameOrAlias(name)) {
        return preset;
      }
    }

    return null;
  }
}
